// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

/**
 * Key represents a key.
 * https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
 */
export enum Key {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * All kinds of Keys
     */
    KeySpace = 32,
    Key0 = 48,
    Key1 = 49,
    Key2 = 50,
    Key3 = 51,
    Key4 = 52,
    Key5 = 53,
    Key6 = 54,
    Key7 = 55,
    Key8 = 56,
    Key9 = 57,
    KeyA = 65,
    KeyB = 66,
    KeyC = 67,
    KeyD = 68,
    KeyE = 69,
    KeyF = 70,
    KeyG = 71,
    KeyH = 72,
    KeyI = 73,
    KeyJ = 74,
    KeyK = 75,
    KeyL = 76,
    KeyM = 77,
    KeyN = 78,
    KeyO = 79,
    KeyP = 80,
    KeyQ = 81,
    KeyR = 82,
    KeyS = 83,
    KeyT = 84,
    KeyU = 85,
    KeyV = 86,
    KeyW = 87,
    KeyX = 88,
    KeyY = 89,
    KeyZ = 90,
    KeyReturn = 13,
    KeyEscape = 27,
    KeyDelete = 46,
    KeyTab = 9,
    KeyLeft = 37,
    KeyRight = 39,
    KeyUp = 38,
    KeyDown = 40,
    KeyF1 = 112,
    KeyF2 = 113,
    KeyF3 = 114,
    KeyF4 = 115,
    KeyF5 = 116,
    KeyF6 = 117,
    KeyF7 = 118,
    KeyF8 = 119,
    KeyF9 = 120,
    KeyF10 = 121,
    KeyF11 = 122,
    KeyF12 = 123,
    KeyF13 = 124,
    KeyF14 = 125,
    KeyF15 = 126,
    KeyF16 = 127,
    KeyF17 = 128,
    KeyF18 = 129,
    KeyF19 = 130,
    KeyF20 = 131,
};

/**
 * Modifier represents a modifier.
 * https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey
 */
export enum Modifier {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * All kinds of Modifiers
     */
    ModAlt = 1,
    ModCtrl = 2,
    ModShift = 4,
    ModWin = 8,
};
