// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function GetExecutableDir(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(28538388) as any;
    return $resultPromise;
}

export function GetProp(group: string, key: string): Promise<[any, boolean]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(271634336, group, key) as any;
    return $resultPromise;
}

export function ReadConfig(): Promise<[{ [_: string]: any }, boolean]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3867282341) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        $result[0] = $$createType0($result[0]);
        return $result;
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
