// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function GetWindowNames(): Promise<string[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1914094522) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function StartWatchingFocus(windowName: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4189685661, windowName) as any;
    return $resultPromise;
}

export function StopWatchingFocus(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1414812021) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
