// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hotkey$0 from "../../../golang.design/x/hotkey/models.js";

/**
 * ChangeHotkey changes the hotkey with the given name to the new modifiers and key.
 */
export function ChangeHotkey(name: string, modifiers: hotkey$0.Modifier[], key: hotkey$0.Key): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2833911293, name, modifiers, key) as any;
    return $resultPromise;
}

/**
 * Shutdown unregisters all hotkeys.
 */
export function RegisterHotkey(name: string, modifiers: hotkey$0.Modifier[], key: hotkey$0.Key, event: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(976747080, name, modifiers, key, event) as any;
    return $resultPromise;
}

/**
 * UnregisterAll unregisters all hotkeys.
 */
export function UnregisterAll(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3410217180) as any;
    return $resultPromise;
}
