// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class Monitor {

    /** Creates a new Monitor instance. */
    constructor($$source: Partial<Monitor> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Monitor instance from a string or object.
     */
    static createFrom($$source: any = {}): Monitor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Monitor($$parsedSource as Partial<Monitor>);
    }
}
